import {createTheme} from '@shopify/restyle';
import colors from './colors';
import {RFValue, RHValue} from 'utils';
import fonts from './fonts';

const theme = createTheme({
  colors: {
    primary: colors.softPeach,
    secondary: colors.zest,
    warning: colors.tulipTree,
    error: colors.guardsmanRed,
    errorBackground: colors.pippin,
    background: colors.blueStone,
    disabled: colors.cararra,
    placeholder: colors.silver,
    border: colors.alto,
    white: colors.white,
    black: colors.black,
  },
  spacing: {
    xs: RHValue(4),
    s: RHValue(8),
    m: RHValue(16),
    l: RHValue(24),
    xl: RHValue(32),
    xxl: RHValue(40),
  },
  textVariants: {
    h1: {
      fontSize: RFValue(30),
      fontFamily: fonts.bold,
    },
    h2: {
      fontSize: RFValue(26),
      fontFamily: fonts.bold,
    },
    button: {
      fontSize: RFValue(18),
      fontFamily: fonts.bold,
      color: 'primary',
    },
    error: {
      fontSize: RFValue(14),
      fontFamily: fonts.regular,
      color: 'error',
    },
    label: {
      fontSize: RFValue(15),
      fontFamily: fonts.medium,
      color: 'primary',
      marginBottom: 's',
    },
    defaults: {
      fontSize: RFValue(16),
      fontFamily: fonts.medium,
      color: 'primary',
    },
  },
  buttonVariants: {
    search: {
      width: RHValue(45),
      height: RHValue(45),
      borderRadius: RHValue(8),
    },
    activeSelectorItem: {
      width: '100%',
      height: RHValue(40),
      backgroundColor: 'secondary',
      paddingVertical: 's',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 0,
      marginTop: 0,
    },
    inActiveSelectorItem: {
      width: '100%',
      height: RHValue(40),
      backgroundColor: 'background',
      paddingVertical: 's',
      justifyContent: 'center',
      alignItems: 'center',
      borderRadius: 0,
      marginTop: 0,
    },
    disabled: {
      width: '100%',
      height: RHValue(50),
      backgroundColor: 'primary',
      paddingVertical: 's',
      borderRadius: RHValue(8),
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 's',
    },
    userCard: {
      height: RHValue(80),
      backgroundColor: 'background',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: RHValue(8),
      borderColor: 'secondary',
      borderWidth: 2,
      paddingHorizontal: 'l',
      marginBottom: 'm',
      flexWrap: 'wrap',
    },
    backButton: {
      width: RHValue(45),
      height: RHValue(45),
      borderRadius: RHValue(45) / 2,
      backgroundColor: 'background',
      alignItems: 'center',
      justifyContent: 'center',
    },
    defaults: {
      width: '100%',
      height: RHValue(50),
      backgroundColor: 'secondary',
      paddingVertical: 's',
      borderRadius: RHValue(8),
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 's',
    },
  },
  inputVariants: {
    error: {
      backgroundColor: 'errorBackground',
      borderColor: 'error',
      borderRadius: RHValue(8),
      width: '100%',
      height: RHValue(45),
    },
    multiline: {
      backgroundColor: 'white',
      color: 'background',
      borderColor: 'border',
      borderRadius: RHValue(8),
      width: '100%',
      height: RHValue(100),
      paddingTop: 's',
      marginBottom: 'm',
    },
    multilineError: {
      backgroundColor: 'errorBackground',
      color: 'errorBackground',
      borderColor: 'error',
      borderRadius: RHValue(8),
      width: '100%',
      height: RHValue(100),
      paddingTop: 's',
      marginBottom: 'm',
    },
    defaults: {
      backgroundColor: 'white',
      color: 'background',
      borderColor: 'border',
      borderRadius: RHValue(8),
      width: '100%',
      height: RHValue(45),
      marginBottom: 'm',
    },
  },
});

export type Theme = typeof theme;
export default theme;
